# Generated by Django 2.2.4 on 2019-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='aboutperson',
            name='picture',
        ),
        migrations.AddField(
            model_name='aboutperson',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutperson',
            name='about',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='aboutperson',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
