# Generated by Django 2.2.4 on 2019-11-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191105_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.TextField(choices=[('github', 'GitHub'), ('facebook-f', 'Facebook'), ('twitter', 'Twitter'), ('reddit-alien', 'Reddit'), ('linkedin-in', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=10)),
                ('url', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.AboutPerson')),
            ],
        ),
    ]
